# Generated by Django 5.2.6 on 2025-09-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.counselor')),
            ],
        ),
    ]
