# Generated by Django 5.2.6 on 2025-09-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointmentslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='score',
        ),
    ]
