# Generated by Django 5.2.5 on 2025-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_peerchatsession_peerchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
